name: Tubify
options:
  bundleIdPrefix: com.tubify
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
  configs:
    Debug:
      ENABLE_HARDENED_RUNTIME: NO
    Release:
      ENABLE_HARDENED_RUNTIME: YES

targets:
  Tubify:
    type: application
    platform: macOS
    sources:
      - path: Tubify
        excludes:
          - "*.entitlements"
          - "Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tubify.app
        ENABLE_APP_SANDBOX: NO
        INFOPLIST_FILE: Tubify/Info.plist
        CODE_SIGN_ENTITLEMENTS: Tubify/Tubify.entitlements
        PRODUCT_NAME: Tubify
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"

  TubifyTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: TubifyTests
    dependencies:
      - target: Tubify
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tubify.tests
        PRODUCT_NAME: TubifyTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Tubify.app/Contents/MacOS/Tubify"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES
